version: '3'

services:
  gotenberg:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        GOLANG_VERSION: 1.24.0
        PDFCPU_VERSION: v0.9.1
        GOTENBERG_VERSION: latest
        GOTENBERG_USER_GID: 1000
        GOTENBERG_USER_UID: 1001
        NOTO_COLOR_EMOJI_VERSION: 2.047
        PDFTK_VERSION: v3.3.3
    ports:
      - "3000:3000"
    restart: unless-stopped
