services:
  donue-converter-server:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        GOLANG_VERSION: 1.24.0
        PDFCPU_VERSION: v0.9.1
        GOTENBERG_VERSION: latest
        GOTENBERG_USER_GID: 1000
        GOTENBERG_USER_UID: 1001
        NOTO_COLOR_EMOJI_VERSION: 2.047
        PDFTK_VERSION: v3.3.3
    container_name: donue-converter-server
    ports:
      - '4300:3000'
    restart: unless-stopped
    networks:
      - business-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

networks:
  business-network:
    external: true
